import json
import yaml

value = {
    "data&tags_after_send": [":(", ":)", ":v", "?", "??", "???", "...", "❤", "❤❤", "🤔", "😁", "😂", "😂😂", "😂😂😂",
                             "😂😂😂😂", "😂😂😂😂😂",
                             "😂😂😂😂😂😂", "😊", "😍", "😍😍", "😍😍😍", "😒", "😘", "😘😘", "😘😘😘", "🙄",
                             "a bueno",
                             "aaa", "acha", "aff",
                             "ah", "ah bueno", "ah sim", "aha", "aham", "ahh", "ahhh", "aja", "alright", "amém", "amen",
                             "amor", "apa", "are",
                             "asi", "ata", "babe", "baby", "bb", "bem", "bien", "bien y tu", "bjs", "blm", "blz", "bn",
                             "boa", "boa noite",
                             "boa tarde", "bolo", "bom dia", "buenas noches", "bueno", "bueno amor", "buenos días",
                             "bye",
                             "claro", "como",
                             "como estas", "como estas?", "confirm", "confirmar", "cool", "da", "dale", "damn",
                             "de nada",
                             "desculpa", "dime",
                             "donde estas", "é", "e vc", "e vc?", "eh", "ei", "eita", "enserio", "então", "entendi",
                             "esta bien", "eu",
                             "eu sei", "fa", "fala", "Field1", "gm", "gn", "go", "goo", "good", "good morning",
                             "good night", "gpp", "gracias",
                             "ha", "haa", "haan", "haha", "hahah", "hahaha", "hahahah", "hahahaha", "hahahahaha",
                             "hahahahahaha", "hai",
                             "happy birthday", "hehe", "hehehe", "hello", "hey", "hi", "hii", "hiii", "hlo", "hm",
                             "hmm",
                             "hmmm", "hmmmm", "ho",
                             "holaa", "holaaa", "how", "huh", "hum", "humm", "hy", "i know", "i love you", "idk",
                             "ight",
                             "igual", "ik", "isso",
                             "iy", "iya", "iya sayang", "iyaa", "iyaaa", "iyah", "iyh", "iyo", "ja", "jaja", "jajaj",
                             "jajajaj", "jajajaja",
                             "jajajajaj", "jajajajaja", "jajajajajaja", "jajajajajajaja", "jajajja", "jajja", "jeje",
                             "jejeje", "ka", "ki",
                             "kk", "kkk", "kkkk", "kkkkk", "kkkkkk", "kkkkkkk", "kkkkkkkk", "kkkkkkkkk", "kkkkkkkkkk",
                             "kkkkkkkkkkk",
                             "kkkkkkkkkkkk", "knp", "konfirmasi", "kya", "la", "linda", "lmao", "lol", "ma", "mami",
                             "mañana", "mande", "mano",
                             "mds", "me", "me too", "mhm", "mi", "mi amor", "mira", "mm", "mmm", "mmmm", "mo",
                             "morning",
                             "my", "na", "nada",
                             "nah", "nao", "não", "não sei", "nd", "ne", "né", "neh", "nhi", "ni", "nice", "nn", "no",
                             "no se", "noo", "nooo",
                             "nop", "nope", "nose", "nossa", "nothing", "obg", "obrigada", "obrigado", "oh", "oh ok",
                             "ohh",
                             "ohhh", "ohk",
                             "oi", "oie", "oii", "oiii", "ok", "okay", "oke", "okey", "oki", "okk", "okok", "ola",
                             "omg",
                             "oo", "ooi", "opa",
                             "opo", "oq", "owh", "oye", "pero", "ping", "po", "pois é", "porque", "porque?", "pq",
                             "pq?",
                             "pues", "pues si",
                             "q bom", "q haces", "que", "que bien", "que bom", "que bueno", "que haces", "que haces?",
                             "que?", "re", "really",
                             "rs", "rsrs", "sa", "same", "sayang", "sei", "sério", "serio", "sh", "si", "si amor",
                             "sii",
                             "siii", "siiii",
                             "sim", "sip", "sisi", "sla", "smh", "so", "sorry", "ss", "streaks", "sup", "sure", "ta",
                             "tá",
                             "ta bom",
                             "ta certo", "tabom", "tbm", "tchau", "te amo", "te quiero", "tendi", "thank you", "thanks",
                             "to", "tu", "tudo bem",
                             "ty", "udah", "uhum", "va", "vai", "vale", "vc", "vdd", "verdade", "viu", "vou", "wait",
                             "we",
                             "what", "what?",
                             "what's up", "why", "why?", "wkwk", "wkwkwk", "wow", "wtf", "wya", "wyd", "xd", "xq",
                             "y eso",
                             "y tu", "y tu?",
                             "ya", "yah", "yang", "ye", "yea", "yeah", "yep", "yes", "yh", "yo", "you", "yup", "true",
                             "iye", "yank", "okee",
                             "udh", "gk", "syg", "ooo", "wkwkw", "siap", "amin", "dalem", "alhamdulillah", "ada", "yaa",
                             "pong", "wkwkwkwk",
                             "iyoo", "ora", "otw", "hhhh", "ap", "oalah", "hhh", "yy", "hooh", "makasih", "hh", "ga",
                             "gak",
                             "wkwkwkw", "sipp",
                             "ia", "iya syg", "heeh", "-_-", "maaf", "hay", "ouh", "assalamualaikum", "iya yang",
                             "knpa",
                             "yoi", "mlm", "iyee",
                             "yaudah", "hhhhh", "yyy", "siip", "engga", "oooo", "belum", "ea", "ayu", "woy", "apa?",
                             "iyaiya", "knp?", "okeee",
                             "👍", "tes", "mau", "hahahha", "yoo", "dmna", "lagi apa", "lah", "kenapa", "beb", "hahaa",
                             "yu", "in"]}
json_data = json.dumps(value)
with open("./check_value.yml", "w") as yaml_f:
    yaml_data = yaml.dump(json_data, yaml_f)
